const { chromium } = require('playwright')
;(async () => {
  const browser = await chromium.launch({ headless: true })
  const page = await browser.newPage()
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.goto('http://127.0.0.1:5173/')
  await page.waitForTimeout(1000)
  await page.screenshot({ path: 'sc_verify_header.png', clip: { x: 0, y: 0, width: 500, height: 70 } })
  await browser.close()
  console.log('done')
})()
